db-uri = "postgres://authenticator:lanka_local_dev@127.0.0.1:5432/lanka_monitor"
db-schemas = "public"
db-anon-role = "anon"
db-extra-search-path = "public"
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
server-host = "127.0.0.1"
server-port = 54321
